services: 
  # starting up main krill container
  krill:
    container_name: krill
    image: nlnetlabs/krill
    volumes:
      - rsync_repo:/var/krill/data/repo/rsync/
      - ../../configs/krill.conf:/var/krill/data/krill.conf
      - ../../../key_setup/testbed_keys:/var/lib/bgpsec-keys
    networks:
      bgp:
        ipv4_address: 10.0.0.10
    healthcheck: 
      test: ["CMD", "wget", "http://10.0.0.10:3000/health", "-O", "/dev/null"]
      interval: 10s
      retries: 5
    depends_on:
      - rsyncd

  # using second krill container to add certificates to Krill
  krillc:
    container_name: krillc
    image: nlnetlabs/krill
    volumes:
      - ../../scripts/sign_csr.sh:/opt/sign_csr.sh
      - ../../../key_setup/testbed_keys:/var/lib/bgpsec-keys
      - rsync_repo:/var/krill/data/repo/rsync/
    command: >
      /bin/bash -c "/opt/sign_csr.sh"
    networks:
      bgp:
        ipv4_address: 10.0.0.9
    depends_on: 
      krill:
        condition: service_healthy    

  # sharing tal file between krill and routinator
  tal_share:
    container_name: tal_share
    build:
      context: ../../../docker_images/tal_share
      network: host
    networks:
      bgp:
        ipv4_address: 10.0.0.11
    volumes:
      - rsync_ta:/share/ta
    depends_on:
      krillc:
        condition: service_completed_successfully

  # rsync container to allow routinator to pull relevant files from krill repository
  rsyncd:
    container_name: rsyncd
    image: vimagick/rsyncd 
    networks:
      bgp:
        ipv4_address: 10.0.0.12
    volumes:
      - ../../configs/rsyncd.conf:/etc/rsyncd.conf
      - rsync_repo:/share/repo:ro
      - rsync_ta:/share/ta:ro

  # start up routinator with configuration that points to folder with krill tal
  routinator:
    container_name: routinator
    image: nlnetlabs/routinator
    command: "--config /etc/routinator.conf server --rtr 10.0.0.14:3323 --http 10.0.0.14:8323 --http 10.0.0.14:9556"
    volumes:
      - ../../configs/routinator.conf:/etc/routinator.conf
      - rsync_ta:/home/routinator/krill-tal
    networks:
      bgp:
        ipv4_address: 10.0.0.14
    healthcheck:
      test: ["CMD", "wget", "http://10.0.0.14:8323/status", "-O", "/dev/null"]
      interval: 10s
      retries: 5
    depends_on: 
      krillc:
        condition: service_completed_successfully    
      tal_share:
        condition: service_completed_successfully    
  
  srx_server:
    container_name: srx_server
    image: srx_server
    build:
      context: ../../../docker_images/srx_server
      network: host
    volumes:
      - ../../configs/srx_server.conf:/etc/srx_server.conf
      - ../../configs/srxcryptoapi_server.conf:/usr/local/etc/srxcryptoapi.conf
    networks:
      bgp:
        ipv4_address: 10.0.0.15
    depends_on:
      routinator:
        condition: service_healthy


  bgpsec_io:
    container_name: bgpsec_io
    build:
      context: ../../../docker_images/bgpsec-io
      network: host
    networks:
      bgp:
        ipv4_address: 10.0.0.8
    volumes:
      - ../../../key_setup/testbed_keys:/var/lib/bgpsec-keys
      - ../../../scripts/experiment-1-scalability/sending-prefix:/opt/scripts/
    entrypoint: ["/bin/bash", "-c", "tail -f /dev/null"]

  quaggasrx_00:
    container_name: quaggasrx_00
    image: quaggasrx
    build:
      context: ../../../docker_images/quaggasrx-bgpsec
      network: host
    volumes:
      - ../../../key_setup/testbed_keys:/var/lib/bgpsec-keys
      - ../../configs/quaggasrx-bgpsec/quagga_as64600.conf:/etc/quagga.conf
      - rsync_ta:/etc/routinator/krill-tal
      - ../../configs/srxcryptoapi.conf:/usr/local/etc/srxcryptoapi.conf
      - ../../../scripts/experiment-1-scalability/measuring-prefix-arrival:/opt/scripts/
      - ../../../scripts/experiment-1-scalability/experiments_results/quaggasrx_00:/opt/experiment_output
    networks:
      bgp:
        ipv4_address: 10.0.0.100
    depends_on:
      - srx_server

  quaggasrx_01:
    container_name: quaggasrx_01
    image: quaggasrx
    build:
      context: ../../../docker_images/quaggasrx-bgpsec
      network: host
    volumes:
      - ../../../key_setup/testbed_keys:/var/lib/bgpsec-keys
      - ../../configs/quaggasrx-bgpsec/quagga_as64601.conf:/etc/quagga.conf
      - rsync_ta:/etc/routinator/krill-tal
      - ../../configs/srxcryptoapi.conf:/usr/local/etc/srxcryptoapi.conf
      - ../../../scripts/experiment-1-scalability/measuring-prefix-arrival:/opt/scripts/
      - ../../../scripts/experiment-1-scalability/experiments_results/quaggasrx_01:/opt/experiment_output
    networks:
      bgp:
        ipv4_address: 10.0.0.101
    depends_on:
      - srx_server

  quaggasrx_02:
    container_name: quaggasrx_02
    image: quaggasrx
    build:
      context: ../../../docker_images/quaggasrx-bgpsec
      network: host
    volumes:
      - ../../../key_setup/testbed_keys:/var/lib/bgpsec-keys
      - ../../configs/quaggasrx-bgpsec/quagga_as64602.conf:/etc/quagga.conf
      - rsync_ta:/etc/routinator/krill-tal
      - ../../configs/srxcryptoapi.conf:/usr/local/etc/srxcryptoapi.conf
      - ../../../scripts/experiment-1-scalability/measuring-prefix-arrival:/opt/scripts/
      - ../../../scripts/experiment-1-scalability/experiments_results/quaggasrx_02:/opt/experiment_output
    networks:
      bgp:
        ipv4_address: 10.0.0.102
    depends_on:
      - srx_server

  quaggasrx_03:
    container_name: quaggasrx_03
    image: quaggasrx
    build:
      context: ../../../docker_images/quaggasrx-bgpsec
      network: host
    volumes:
      - ../../../key_setup/testbed_keys:/var/lib/bgpsec-keys
      - ../../configs/quaggasrx-bgpsec/quagga_as64603.conf:/etc/quagga.conf
      - rsync_ta:/etc/routinator/krill-tal
      - ../../configs/srxcryptoapi.conf:/usr/local/etc/srxcryptoapi.conf
      - ../../../scripts/experiment-1-scalability/measuring-prefix-arrival:/opt/scripts/
      - ../../../scripts/experiment-1-scalability/experiments_results/quaggasrx_03:/opt/experiment_output
    networks:
      bgp:
        ipv4_address: 10.0.0.103
    depends_on:
      - srx_server

  quaggasrx_04:
    container_name: quaggasrx_04
    image: quaggasrx
    build:
      context: ../../../docker_images/quaggasrx-bgpsec
      network: host
    volumes:
      - ../../../key_setup/testbed_keys:/var/lib/bgpsec-keys
      - ../../configs/quaggasrx-bgpsec/quagga_as64604.conf:/etc/quagga.conf
      - rsync_ta:/etc/routinator/krill-tal
      - ../../configs/srxcryptoapi.conf:/usr/local/etc/srxcryptoapi.conf
      - ../../../scripts/experiment-1-scalability/measuring-prefix-arrival:/opt/scripts/
      - ../../../scripts/experiment-1-scalability/experiments_results/quaggasrx_04:/opt/experiment_output
    networks:
      bgp:
        ipv4_address: 10.0.0.104
    depends_on:
      - srx_server





  
    
volumes:
  rsync_repo:

  rsync_ta:

networks:
  bgp:
    driver_opts:
      com.docker.network.bridge.name: br-bgp 
    ipam:
      driver: default
      config: 
        - subnet: 10.0.0.0/8
